### ISSUE TITLE
The vlan-patches-3 branch of ikelos/openvpn is broken

### ISSUE THREAD

**Issue by devplayer0** [nategraf/Naumachia#28]
There's a bug, along with some missing code, which means that this branch doesn't work at all (even with `vlan-tagging` disabled!):

- The logic [here](https://github.com/ikelos/openvpn/blob/a5901d74887db86c6efd7c4d699fa5a4f9d3c676/src/openvpn/mroute.c#L309) means that all frames are detected as VLAN tagged but with an invalid header, meaning no traffic is ever dispatched on the server side TAP!
- A call to `vlan_remove_8021q_tag` is missing [here](https://github.com/ikelos/openvpn/blob/a5901d74887db86c6efd7c4d699fa5a4f9d3c676/src/openvpn/multi.c#L2768) which means packets sent to clients are left with VLAN tags still attached!
- The PVID set by the `vlan-pvid` option is not applied to incoming (client -> server) packets [here](https://github.com/ikelos/openvpn/blob/a5901d74887db86c6efd7c4d699fa5a4f9d3c676/src/openvpn/multi.c#L2636)

See my commits at https://github.com/devplayer0/openvpn/tree/vlan-patches-v3 for fixes (or revert back to `vlan-patches-v2`. Hopefully the correct code will be merged into OpenVPN soon so a fork will no longer be required.

**Comment by nategraf** [comment]
Sorry for the slow response I haven't really been looking at issues. :sweat_smile: Ya I saw that a little while back and changed back to the v2 branch
