### ISSUE TITLE
Getting error in generating openvpn config 

### ISSUE THREAD

**Issue by bhaviksec** [nategraf/Naumachia#37]
./registrar-cli mitm add sender
Traceback (most recent call last):
  File "/home/seccon/Naumachia/./registrar-cli", line 47, in <module>
    regi.add_cert(args.client)
  File "/home/seccon/Naumachia/registrar/app/registrar.py", line 188, in add_cert
    [self.easyrsa, 'build-client-full', cn, 'nopass'],
  File "/home/seccon/Naumachia/registrar/app/registrar.py", line 146, in easyrsa
    return path.join(self.easyrsa_dir, 'easyrsa')
  File "/usr/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Note: I am running the above command before docker-compose up 

Naumachia/pentest# ls -al
total 16
drwxr-xr-x  3 root root 4096 Oct 29 00:06 .
drwxr-xr-x 11 root root 4096 Oct 28 23:53 ..
-rwxrwxrwx  1 root root  661 Oct 28 23:58 docker-coompose.yml
drwxr-xr-x  2 root root 4096 Oct 29 00:06 sender

Below is docker compose file 

Not sure what I am missing 

Also when i run docker-compose up I get below error 

docker-compose up -d
Creating network "pentest_default" with driver "l2bridge"

ERROR: plugin "l2bridge" not found

Appreciate some help

**Comment by theevilsyn** [comment]
Hi,

I see a couple of issues here. 

1. The l2bridge driver must be installed before trying to bring naumachia up.
2. The registrar-cli is should be run after bringing the compose up.

I would suggest you to follow the steps in the repo's readme on the drivers and install them, and then do a docker-compose up. Once the registrar container is up through compose, the registrar-cli should work flawlessly.

**Comment by bhaviksec** [comment]
Thanks a lot. Fixed the driver issue. I have few queries in setting up the environment 

As I can see that config.py can be use to build the docker-compose.yml file. I tried that and I got a complete different docker-compose.yml file 

Docker-compose from config.py script 

version: '2.4'

services:
    # Bootstrapper is an arbitrary container run on the host network to mount the host netns.
    # See https://github.com/nategraf/Naumachia/issues/31 for more details.
    bootstrapper:
        image: alpine
        network_mode: host
        command: ["/bin/true"]

    openvpn-pentest:
        build:
            context: ./openvpn/build
            args:
                - OVPN_REPO_URL
                - OVPN_REPO_BRANCH
        image: naumachia/openvpn
        depends_on:
            - bootstrapper
        cap_add:
            - NET_ADMIN
        restart: unless-stopped
        networks:
            default:
            internal:
        ports:
            - "2000:1194/udp"
        volumes:
            - ./openvpn/config/pentest:/etc/openvpn
            - ./logs/pentest:/var/log
            - /var/run/docker/netns/default:/var/run/netns/host
            - ./openvpn/scripts:/scripts:ro
        environment:
            - REDIS_HOSTNAME
            - REDIS_PORT
            - REDIS_DB
            - REDIS_PASSWORD
            - NAUM_FILES=["pentest/docker-compose.yml"]
            - NAUM_CHAL="pentest"
            - PUSH_ADDR=172.30.0.14
            - PUSH_MASK=255.255.255.240


    registrar:
        build: ./registrar
        image: naumachia/registrar
        volumes:
            - ./openvpn/config/:/var/openvpn
            - ./registrar/app:/app:ro


Docker-compose.yml from challenge repo 

version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    arthur: &knight
        <<: *limits
        build: ./actor
        image: naumachia/listen.actor
        env_file: chal.env
        environment:
            CHARACTER: Arthur
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.30.0.2

    bedevere:
        <<: *knight
        environment:
            CHARACTER: Bedevere
        networks:
            default:
                ipv4_address: 172.30.0.3

    robin:
        <<: *knight
        environment:
            CHARACTER: Robin
        networks:
            default:
                ipv4_address: 172.30.0.4

    bridgekeeper:
        <<: *knight
        environment:
            CHARACTER: Bridgekeeper
        networks:
            default:
                ipv4_address: 172.30.0.5

    lancelot:
        <<: *knight
        environment:
            CHARACTER: Lancelot
        networks:
            default:
                ipv4_address: 172.30.0.6

    galahad:
        <<: *knight
        environment:
            CHARACTER: Galahad
        networks:
            default:
                ipv4_address: 172.30.0.7

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28

So I was expecting the network parameters to be configured. Am I missing something . 
Because of this I tried to confugure the yml file manually but then the resgistrar-cli and also the application is not coming up

**Comment by bhaviksec** [comment]
After running the docker-compose on root dir get the below error 

Traceback (most recent call last):
  File "/usr/bin/pip3", line 33, in <module>
    sys.exit(load_entry_point('pip==20.3.4', 'console_scripts', 'pip3')())
  File "/usr/bin/pip3", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: pip
ERROR: Service 'openvpn-pentest' failed to build: The command '/bin/sh -c pip3 install -r requirements.txt && rm requirements.txt' returned a non-zero code: 1

Its unable to build openvpn package

**Comment by bhaviksec** [comment]
This was due to older release of source image in dockerfile . Fixed it
