### ISSUE TITLE
Cannot find tap0 interface 

### ISSUE THREAD

**Issue by bhaviksec** [nategraf/Naumachia#38]
the openvpn service fails with below error 
openvpn-pentest_1  | Cannot find device "tap0"
The reason is because the container does not have tap0 interface as it has only eth0 interface . The naumachia-start script inside openvpn does below stuff which is the cause 

 Define the name of the TAP interface.
 for example tap="tap0".
tap="tap0"

How to fix this ?

I tried by renmaing tap=eth0 then it gives the below error 

naumachia_bootstrapper_1 exited with code 0
openvpn-pentest_1  | /scripts/naumachia-start: line 22: openvpn: command not found
openvpn-pentest_1  | Traceback (most recent call last):
openvpn-pentest_1  |   File "/scripts/naumachia/register_vpn.py", line 6, in <module>
openvpn-pentest_1  |     from common import get_env
openvpn-pentest_1  |   File "/scripts/naumachia/common.py", line 6, in <module>
openvpn-pentest_1  |     from db import DB
openvpn-pentest_1  |   File "/scripts/naumachia/db.py", line 1, in <module>
openvpn-pentest_1  |     from trol import Database, Model, Property, Set, Hash, List, Lock, serializers, deserializers
openvpn-pentest_1  | ModuleNotFoundError: No module named 'trol'
openvpn-pentest_1  | naumachia-start complete: now running ovpn_run

Appreciate some help

**Comment by bhaviksec** [comment]
Was able to fix the tap0 interface error . Now the registrar is not stable and it crashes with below error 

Attaching to naumachia_bootstrapper_1, naumachia_redis_1, naumachia_registrar_1, naumachia_manager_1, naumachia_openvpn-pentest_1
openvpn-pentest_1  | 2021-10-31 12:13:37 TUN/TAP device tap0 opened
openvpn-pentest_1  | 2021-10-31 12:13:37 Persist state set to: ON
naumachia_bootstrapper_1 exited with code 0
openvpn-pentest_1  | naumachia-start complete: now running ovpn_run
openvpn-pentest_1  | Checking IPv6 Forwarding
openvpn-pentest_1  | Sysctl error for disable_ipv6, please run docker with '--sysctl net.ipv6.conf.all.disable_ipv6=0'
openvpn-pentest_1  | Sysctl error for default forwarding, please run docker with '--sysctl net.ipv6.conf.default.forwarding=1'
openvpn-pentest_1  | Sysctl error for all forwarding, please run docker with '--sysctl net.ipv6.conf.all.forwarding=1'
openvpn-pentest_1  | Running 'openvpn --config /etc/openvpn/openvpn.conf --crl-verify /etc/openvpn/crl.pem '
openvpn-pentest_1  | 2021-10-31 12:13:38 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
naumachia_registrar_1 exited with code 3
naumachia_registrar_1 exited with code 3
naumachia_registrar_1 exited with code 3
naumachia_registrar_1 exited with code 3
naumachia_registrar_1 exited with code 3
naumachia_registrar_1 exited with code 3

**Comment by nategraf** [comment]
Sorry for not seeing this for so long.

I can't quite tell what is happening from the information here. `tap0` is the virtual interface created by OpenVPN when it starts up, so it should exist. `eth0` is the interface created by Docker to link the container network namespace to the Linux bridge for the container's network, and is the Interface over which Internet requests are sent and received.

It appears that in the first case, the main issue is that one of the Python dependencies did not get included int the container. In the second case it appears from the log here that the OpenVPN container is up, but the registrar is failing.

**Comment by nategraf** [comment]
Since it's been about 6 months without further information, I am going to close this issue for now. I am definitely still happy to help.
