### ISSUE TITLE
ERROR: LinkUpCmd failed with exit code 255

### ISSUE THREAD

**Issue by fjramirez1987** [nategraf/Naumachia#40]
I have this error:

ERROR: LinkUpCmd failed with exit code 255
Command: ip netns exec host ip link set vthde8b51ecb0e3 promisc on up
setting the network namespace "host" failed: Invalid argument

**Comment by nategraf** [comment]
Any additional details you can provide will be helpful in tracking down the issue. One thing I will say is this sounds like it may be related to https://github.com/nategraf/Naumachia/issues/31. The [bootstrapper service](https://github.com/nategraf/Naumachia/blob/master/templates/docker-compose.yml.j2#L19-L24) is supposed to take care of setting up the host namespace, but it's possible it failed to do so.

**Comment by fjramirez1987** [comment]
Here are the steps I followed to reproduce the error:
On a machine with Linux server 18.04.6 I have copied the examples from https://github.com/nategraf/Naumachia-challenges along with the config.yml file

I have run ./configure.py and then docker-compose up. In this last step, it gives me an error in https://github.com/nategraf/Naumachia/blob/master/openvpn/build/Dockerfile in the command: RUN pip install -r requirements.txt

I got around that error by changing FROM alpine:3.16 to FROM python:3.10-alpine3.16

After fixing that error all the containers start successfully and the bootstrapper container returns this expected code: naumachia_bootstrapper_1 exited with code 0

I have registered using:
• ./registrar-cli middle add javier
• ./registrar-cli middle get javier > middle.ovpn

On Kali Linux I run without errors:
sudo openvpn /home/kali/Desktop/middle.ovpn

In manager.log I get the following error:

[02/07/23 21:50:03] INFO: New connection 192.168.1.196.65281 to cluster javier@middle
[02/07/23 21:50:03] ERROR: LinkUpCmd failed with exit code 255
Command: ip netns exec host ip link set vth00bb11c51f1d promisc on up
setting the network namespace "host" failed: Invalid argument

[02/07/23 21:50:03] ERROR: Exception in <Worker for b'set' on b'__keyspace@0__:Connection:192.168.1.196.65281:alive'>
Traceback (most recent call last):
  File "/app/listener.py", line 22, in run
    self.fn(self.channel, self.data)
  File "/app/manager.py", line 75, in connection_set
    veth_up(vpn)
  File "/app/veth.py", line 21, in veth_up
    LinkUpCmd(vpn.veth).run()
  File "/app/commands.py", line 27, in run
    subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ip', 'netns', 'exec', 'host', 'ip', 'link', 'set', 'vth00bb11c51f1d', 'promisc', 'on', 'up']' returned non-zero exit status 255.


thank you very much for your help!

**Comment by nategraf** [comment]
Thanks for finding and letting me know about the issue with the base image for the openvpn container. I've fixed that issue in 4773bba.

As for the issue you are seeing. I went through the install process on a fresh computer on Ubuntu 22.04, and did not encounter any issues. Perhaps you might try using a newer distribution?

**Comment by fjramirez1987** [comment]
I have fixed the problem and this has been the cause of my problem:

When I have installed Ubuntu, in the installation process it asks you if you want to install some apps (Docker, Nextcloud, Wekan,...) I have installed Docker and apparently it is installed with Snap changing the name of the Docker service.

For my solution:

DO NOT install Docker via Sanp.

Thanks for the help.
