### ISSUE TITLE
Challenge containers are not generated

### ISSUE THREAD

**Issue by fjramirez1987** [nategraf/Naumachia#41]
I have a problem when executing a challenge. Here are the steps to reproduce the error:

I am using CTFd with the Naumachia plugin to generate the Openvpn configuration file.
The user runs in Kali with no errors:
sudo openvpn /home/kali/Desktop/listen.ovpn

In the manager.log file:
[02/10/23 08:16:32] INFO: New connection 192.168.1.196.61181 to cluster fjramirez7a@listen
[02/10/23 08:16:32] INFO: Activated veth vth97493506ed59 on vpn 97493506ed59

I have been able to see with Portainer that a new network has been created, but I do not see any container being generated with the "Listen" challenge (https://github.com/nategraf/Naumachia-challenges).

I have not seen any errors in the logs except on specific occasions that I have not been able to reproduce:

[02/09/23 21:27:47] INFO: Deleted connection 192.168.1.117.59239 to fjramirez7a@listen
[02/09/23 21:27:47] INFO: No connections to cluster fjramirez7a@listen; Setting timeout for 900 seconds
[02/09/23 21:42:47] INFO: Expired cluster fjramirez7a@listen
[02/10/23 07:19:59] INFO: New connection 192.168.1.196.62109 to cluster fjramirez7a@listen
[02/10/23 07:20:30] ERROR: ComposeCmd failed with exit code 1
Command: docker-compose -p fjramirez7a_listen -f /challenges/listen/docker-compose.yml up -d
Building arthur
1 [internal] load .dockerignore
1 sha256:e5b100a9c6c3f4b38f77e900cfa3d22b0f0aaca9ae96ac3606fb4b6a6a0a9616
1 transferring context: 2B done
1 DONE 0.1s

2 [internal] load build definition from Dockerfile
2 sha256:c8e1cba43610258257d4c98289db7b20c3d733ea43351e233db8c32f1ea61498
2 transferring dockerfile: 153B 0.0s done
2 DONE 0.1s

3 [internal] load metadata for docker.io/library/python:3.5-alpine
3 sha256:f4a8c8ca3136ce915616cdbfd5256249e5bd91742894136dd373ccd6654449ec
3 ERROR: failed to authorize: failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fpython%3Apull&service=registry.docker.io": dial tcp 18.215.138.58:443: i/o timeout

[internal] load metadata for docker.io/library/python:3.5-alpine:

python:3.5-alpine: failed to authorize: failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fpython%3Apull&service=registry.docker.io": dial tcp 18.215.138.58:443: i/o timeout
Service 'arthur' failed to build : Build failed

[02/10/23 07:20:30] WARNING: Retrying failed compose up command: CalledProcessError(1, ['docker-compose', '-p', 'fjramirez7a_listen', '-f', '/challenges/listen/docker-compose.yml', 'up', '-d'])
[02/10/23 07:21:03] ERROR: ComposeCmd failed with exit code 1
Command: docker-compose -p fjramirez7a_listen -f /challenges/listen/docker-compose.yml up -d
Creating network "fjramirez7a_listen_default" with driver "l2bridge"
Building arthur
1 [internal] load .dockerignore
1 sha256:1733be485c7c9e9c364d6c0c3deac80f89f057d02b9a83e6fac48da7f05852c5
1 transferring context: 2B done
1 DONE 0.1s

2 [internal] load build definition from Dockerfile
2 sha256:39a78e96d9ebf33a3f3297126bd144fe9ea0dfb9147a3c3abbe9d2874578ab19
2 transferring dockerfile: 153B done
2 DONE 0.1s

3 [internal] load metadata for docker.io/library/python:3.5-alpine
3 sha256:f4a8c8ca3136ce915616cdbfd5256249e5bd91742894136dd373ccd6654449ec
3 ERROR: failed to authorize: failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fpython%3Apull&service=registry.docker.io": dial tcp 18.215.138.58:443: i/o timeout

[internal] load metadata for docker.io/library/python:3.5-alpine:

python:3.5-alpine: failed to authorize: failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fpython%3Apull&service=registry.docker.io": dial tcp 18.215.138.58:443: i/o timeout
Service 'arthur' failed to build : Build failed

[02/10/23 07:21:03] ERROR: Exception in <Worker for b'set' on b'\_\_keyspace@0__:Connection:192.168.1.196.62109:alive'>
Traceback (most recent call last):
  File "/app/cluster.py", line 40, in cluster_up
    ComposeCmd(ComposeCmd.UP, project=cluster.project, files=vpn.chal.files).run()
  File "/app/commands.py", line 27, in run
    subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker-compose', '-p', 'fjramirez7a_listen', '-f', '/challenges/listen/docker-compose.yml', 'up', '-d']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/listener.py", line 22, in run
    self.fn(self.channel, self.data)
  File "/app/manager.py", line 77, in connection_set
    cluster_up(user, vpn, cluster)
  File "/app/cluster.py", line 44, in cluster_up
    ComposeCmd(ComposeCmd.UP, project=cluster.project, files=vpn.chal.files).run()
  File "/app/commands.py", line 27, in run
    subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker-compose', '-p', 'fjramirez7a_listen', '-f', '/challenges/listen/docker-compose.yml', 'up', '-d']' returned non-zero exit status 1.

**Comment by fjramirez1987** [comment]
I have done some tests and these are the results:

The manager container does not create the challenge containers. I have added the bridge network to the manager container and at that moment the challenge containers are created.

In the same way, the containers created for the challenges (for example the Listen challenge), cannot communicate with each other, they are "isolated". Obviously since Kali is connected to the vpn, the containers are not accessible when ping.

As data, my Ubuntu is in a virtual machine with VirtualBox with the network in bridge mode. I don't think this will be relevant...

PS: I have been able to appreciate that if a claustrer (container) is not created, manager continues to carry out the actions as if it were created and does not notify errors in the log (it only indicates it the first time).

**Comment by nategraf** [comment]
It looks like the build process for the challenge containers is failing.
```
3 [internal] load metadata for docker.io/library/python:3.5-alpine
3 sha256:f4a8c8ca3136ce915616cdbfd5256249e5bd91742894136dd373ccd6654449ec
3 ERROR: failed to authorize: failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fpython%3Apull&service=registry.docker.io": dial tcp 18.215.138.58:443: i/o timeout

[internal] load metadata for docker.io/library/python:3.5-alpine:

python:3.5-alpine: failed to authorize: failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fpython%3Apull&service=registry.docker.io": dial tcp 18.215.138.58:443: i/o timeout
Service 'arthur' failed to build : Build failed
```
It looks like it's failing because the builder cannot contact the Docker registry. Is the Naumachia host (i.e. the one tha manager is on) have full Internet access?

Container builds happen automatically when the first client connects to a challenge if it has not happened yet, but it can also be triggered manually. The `build-challenges.sh` file is one way to do that. Here is a command to just build the `listen` challenge.

More simply, you can do:

```bash
cd challenges/listen
# Use `docker compose` if you installed the Docker plugin version of Compose and `docker-compose` if you have the PyPi version. (The manager currently uses the (older) PyPi version
sudo docker compose build
```

Can you give that a try? If it does work, the containers should then be in the build cache and will not need to be rebuilt. If it does not work, you should see if the error is do to network timeouts and look further into whether your Naumachia host has Internet access.

> PS: I have been able to appreciate that if a claustrer (container) is not created, manager continues to carry out the actions as if it were created and does not notify errors in the log (it only indicates it the first time).

Ya, this definitely needs somewhat better error handling :grimacing:. Unless there is a major bug, reconnecting with the client _should_ result in the manager retrying to build and launch the cluster. If this is not happening, then that's something that needs to be fixed ASAP.

**Comment by fjramirez1987** [comment]
We are progressing…

I have done the following:

```
cd challenges/listen
sudo docker compose build
```
And it has compiled without problems. Containers are now created when users connect to the VPN.

The problem is that the containers are not accessible on the network. There seems to be a problem with l2bridge but I don't see any errors.

In Wireshark no packets show up, I can't ping the containers from Kali. There is no ping from the container terminal to the other devices.


I have tried cloning the repository from https://github.com/nategraf/l2bridge-driver
Then a sudo docker compose up -d getting the following:

```
Creating l2bridge-driver_larry_1 ... done
Creating l2bridge-driver_moe_1 ... done
Attaching to l2bridge-driver_moe_1, l2bridge-driver_larry_1
larry_1 | 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc knockout state UNKNOWN group default qlen 1000
larry_1 | link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
larry_1 | inet 127.0.0.1/8 scope host lo
larry_1 | valid_lft forever preferred_lft forever
larry_1 | 1458: eth0@if1459: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc knockout state UP group default
larry_1 | link/ether 02:42:7d:c1:cb:d4 brd ff:ff:ff:ff:ff:ff link-netnsid 0
larry_1 | inet 192.168.0.3/24 brd 192.168.0.255 scope global eth0
larry_1 | valid_lft forever preferred_lft forever
larry_1 | default via 192.168.0.1 dev eth0
larry_1 | 192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.3
larry_1 | Running ping -c 5 moe
larry_1 | PING moe (192.168.0.2) 56(84) bytes of data.
moe_1 | 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc knockout state UNKNOWN group default qlen 1000
moe_1 | link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
moe_1 | inet 127.0.0.1/8 scope host lo
moe_1 | valid_lft forever preferred_lft forever
moe_1 | 1456: eth0@if1457: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc knockout state UP group default
moe_1 | link/ether 02:42:b9:ad:d5:3a brd ff:ff:ff:ff:ff:ff link-netnsid 0
moe_1 | inet 192.168.0.2/24 brd 192.168.0.255 scope global eth0
moe_1 | valid_lft forever preferred_lft forever
moe_1 | default via 192.168.0.1 dev eth0
moe_1 | 192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.2
moe_1 | Running ping -c 5 larry
moe_1 | PING larry (192.168.0.3) 56(84) bytes of data.
moe_1 |
moe_1 | --- larry ping statistics ---
moe_1 | 5 packets transmitted, 0 received, 100% packet loss, time 4099ms
moe_1 |
larry_1 |
larry_1 | --- moe ping statistics ---
larry_1 | 5 packets transmitted, 0 received, 100% packet loss, time 4099ms
larry_1 |
l2bridge-driver_larry_1 exited with code 1
l2bridge-driver_moe_1 exited with code 1
```

I can't think of any more things... I am very interested in setting up this project for my Ethical Hacking classes. ☹

PS: I have changed to a cloud server to rule out problems in my network... same problems...

**Comment by nategraf** [comment]
Ok, glad the build issue was resolved.

On the networking issue, the first placed I'd look is to see if your iptables (or any other firewalls installed) are allowing the traffic.

One option is to disable enforcement of iptables rules for L2 traffic. This script in the repo does this: https://github.com/nategraf/Naumachia/blob/master/disable-bridge-nf-iptables.sh

**Comment by fjramirez1987** [comment]
Simple as:

```
chmod +x ./disable-bridge-nf-iptables.sh
./disable-bridge-nf-iptables.sh
```

WORKS!!

Thank you very much for your help. On a big project!

**Comment by nategraf** [comment]
🙌🔥
