### ISSUE TITLE
Openvpn build fails on incompatible python

### ISSUE THREAD

**Issue by pssmatos** [nategraf/Naumachia#45]
You have changed the `Dockerfile` base image for the `openvpn` build, to include `python 3.10`, but in the `apk` command, you are still installing python and pip3, which causes a build error:

    fetch http://dl-4.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
    ERROR: unable to select packages:
    python3-3.10.11-r0:
        breaks: py3-pip-23.1.2-r0[python3~3.11]
        satisfies: world[python3]
                py3-pip-23.1.2-r0[python3]
                py3-setuptools-59.4.0-r0[python3]
                py3-parsing-2.4.7-r3[python3]
                py3-packaging-21.3-r0[python3]
                py3-ordered-set-4.0.2-r3[python3]
                py3-more-itertools-8.13.0-r0[python3]
                py3-appdirs-1.4.4-r3[python3]
                py3-six-1.16.0-r1[python3]`

**Comment by nategraf** [comment]
Oof. Ok, I'll take a look within the next couple of days and get this fixed.

**Comment by nategraf** [comment]
Alright, I believe I've fixed this with fd7a0cc862645186cc8451df615cd6845ed59adf

Let me know if this resolves the issue for you. And thank you for opening an issue! (I found a number of other bit-rot style build issues as well in this and the [Naumachia-challenges](https://github.com/nategraf/Naumachia-challenges) repo)

**Comment by pssmatos** [comment]
Sorry for the late response, yes it fixed the problem i had
